module AHB_protocol_single_master #(parameter Addr = 9,parameter DATA = 15) (clk,rst,en,Ext_data_in,HBURST,Ext_addr_in,data_out,error,HWRITE);
input clk,rst;
input [DATA:0]Ext_data_in;
input [Addr:0] Ext_addr_in;
input en;
input [2:0] HBURST;
output [DATA:0]data_out;
output error;
output HWRITE;
wire [Addr:0] HADDR;
wire [Addr:0] ADDR;
wire HREADY;
wire HRESP;
wire [DATA:0]HRDATA;
wire [DATA:0]HDATA;
wire  HWRITE;
wire burst;
wire  [1:0] HTRANS;
wire  [2:0] HSIZE;
wire  [DATA:0]HWDATA;
wire [1:0]HSELx;
wire [DATA:0] HRDATA_0;
wire [DATA:0]HRDATA_1;
wire [DATA:0]HRDATA_2;
wire [DATA:0]HRDATA_3;
wire HRESP_0;
wire HRESP_1;
wire HRESP_2;
wire HRESP_3;
wire HREADYOUT_0;
wire HREADYOUT_1;
wire HREADYOUT_2;
wire HWRITE1;
wire HREADYOUT_3;
assign HWDATA = Ext_data_in;
assign HADDR = Ext_addr_in;
assign data_out = HRDATA; 
assign HWRITE = en;
assign error = E_flag;
manager m1 (.clk(clk),.rst(rst),.HREADY(HREADY),.HADDR(HADDR),.HWDATA(HWDATA),.HRESP(HRESP),.HBURST(HBURST),.HWRITE(HWRITE),.HSIZE(HSIZE),.ADDR(ADDR),.HTRANS(HTRANS),.HDATA(HDATA),.E_flag(E_flag),.burst(burst),.HWRITE1(HWRITE1));
decoder d1 (.ADDR(ADDR),.burst(burst),.HREADY(HREADY),.HSELx(HSELx));
multiplexor mux1(.HRDATA_0(HRDATA_0),.HRDATA_1(HRDATA_1),.HRDATA_2(HRDATA_2),.HRDATA_3(HRDATA_3),.HRESP_0(HRESP_0),.HRESP_1(HRESP_1),.HRESP_2(HRESP_2),.HRESP_3(HRESP_3),.HREADYOUT_0(HREADYOUT_0),.HREADYOUT_1(HREADYOUT_1),.HREADYOUT_2(HREADYOUT_2),.HREADYOUT_3(HREADYOUT_3),.HSELx(HSELx),.HRDATA(HRDATA),.HRESP(HRESP),.HREADY(HREADY));
subordinate s0 (.clk(clk),.rst(rst),.HSELx(HSELx),.ADDR(ADDR),.HSIZE(HSIZE),.HTRANS(HTRANS),.HWRITE1(HWRITE1),.HBURST(HBURST),.HDATA(HDATA),.HREADYOUT_0(HREADYOUT_0),.HRESP_0(HRESP_0),.HRDATA_0(HRDATA_0));
SUB_2 s1 (.clk(clk),.rst(rst),.HSELx(HSELx),.ADDR(ADDR),.HSIZE(HSIZE),.HTRANS(HTRANS),.HWRITE1(HWRITE1),.HBURST(HBURST),.HDATA(HDATA),.HREADYOUT_1(HREADYOUT_1),.HRESP_1(HRESP_1),.HRDATA_1(HRDATA_1));
SUB_3 s2 (.clk(clk),.rst(rst),.HSELx(HSELx),.ADDR(ADDR),.HSIZE(HSIZE),.HTRANS(HTRANS),.HWRITE1(HWRITE1),.HBURST(HBURST),.HDATA(HDATA),.HREADYOUT_2(HREADYOUT_2),.HRESP_2(HRESP_2),.HRDATA_2(HRDATA_2));
SUB_4 s3 (.clk(clk),.rst(rst),.HSELx(HSELx),.ADDR(ADDR),.HSIZE(HSIZE),.HTRANS(HTRANS),.HWRITE1(HWRITE1),.HBURST(HBURST),.HDATA(HDATA),.HREADYOUT_3(HREADYOUT_3),.HRESP_3(HRESP_3),.HRDATA_3(HRDATA_3));
endmodule
